services:

  mongo:
    build: ./.docker/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

### run -> docker compose up
### abrir docker fora do wsl e startar container